---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
spec:
  targetNamespace: storage
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: prometheus-operator-crds
      namespace: monitoring
  path: ./kubernetes/apps/storage/snapshot-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
