---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./podmonitor.yaml
configMapGenerator:
  - name: flux-instance-helm-values
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
