# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 10m0s
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.2
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    worker:
      config:
        core:
          featureSources:
            - custom
            - kernel
            - pci
            - usb
          labelSources:
            - custom
            - kernel
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device
          pci:
            deviceClassWhitelist:
              - "0108" # NVMe device class id
              - "03"
              - "0b40"
              - "12"
            deviceLabelFields: 
              - class
