---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: recyclarr
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 10m0s
  dependsOn:
    - name: volsync
    - name: rook-ceph-cluster
    - name: external-secrets-stores
  path: ./kubernetes/apps/default/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
