---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      qbittorrent:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.0@sha256:fe26058628e9eb57b542204b76443b7304ed8820151d51b5c285e1828ca175a0
            env:
              TZ: Europe/Sofia
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: qbittorrent
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.0.41
        ports:
          http:
            port: 80
            targetPort: 8080
          bittorrent:
            enabled: true
            port: 50413
            targetPort: 50413
            protocol: TCP

    route:
      app:
        hostnames:
          - qbittorrent.nasenov.dev
          - qb.nasenov.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 80

    persistence:
      config:
        existingClaim: qbittorrent
      media:
        enabled: true
        type: nfs
        server: 192.168.0.15
        path: /mnt/tank/media
        globalMounts:
          - path: /data/downloads
            subPath: downloads
      tmpfs:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            app:
              - path: /tmp
                subPath: tmp
