---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      qbittorrent:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 911
            runAsGroup: 911
            fsGroup: 911
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.0@sha256:3e7c969139da1eaf8d3ccdebd473eefb4e2550d610b88f5a3c866bc34662d89a
            env:
              TZ: Europe/Sofia
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: qbittorrent
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.0.41
        ports:
          http:
            port: 80
            targetPort: 8080
          bittorrent:
            enabled: true
            port: 50413
            targetPort: 50413
            protocol: TCP

    route:
      app:
        hostnames:
          - qb.nasenov.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: qbittorrent
                port: 80

    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: ceph-block
        dataSourceRef:
          apiGroup: volsync.backube
          kind: ReplicationDestination
          name: qbittorrent-dst
        accessMode: ReadWriteOnce
        size: 1Gi
      media:
        enabled: true
        type: nfs
        server: 192.168.0.15
        path: /mnt/tank/media
        globalMounts:
          - path: /data/downloads
            subPath: downloads
