---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      prowlarr:
        type: statefulset

        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              accessMode: ReadWriteOnce
              dataSourceRef:
                apiGroup: volsync.backube
                kind: ReplicationDestination
                name: prowlarr-dst
              size: 1Gi
              storageClass: ceph-block

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 1.33.1.4997@sha256:3bb878cf5d447934f4f3848315f3cf393bdc269eee9f823df34e06768a55ddb3
            env:
              TZ: Europe/Sofia
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 256Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 911
        runAsGroup: 911
        fsGroup: 911
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: prowlarr
        ports:
          http:
            port: 80
            targetPort: 9696

    ingress:
      app:
        className: nginx
        hosts:
          - host: prowlarr.nasenov.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - hosts:
              - prowlarr.nasenov.dev
