---
apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-access-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:wVToVD3dMUN6LFpW/UmWdBtuMT8nA+Fsr8Xf9seRPe1QzfYKCmo77QB67OyFqpRhItfSx914GDZMzzP51eaKE8LC5Kzgq8OT4ZwOGDswVeKivVT1qxfStyogFGSQPw==,iv:LzFYWu5cLLF+sX69y0043Nobw2OZYeyX0ARb2Nwcch8=,tag:T8SoVqhfrzbQbA5uKXubaQ==,type:str]
sops:
    age:
        - recipient: age128pzspekap6pjzu53vzfn9t6xpvazq0z6qxxj79v27mke4urup9qqqhq4t
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBya1VjUkJQUjBQMHZHZGN2
              dkJkVTIxWjhtY3hRUnM0WFFCRDhDZ2U0TWtVCkNpVWhmMDduU3YwNUYwcHY3YUpW
              UTlWNUpsOUthNk9ieWM1ZkNWekJBK3MKLS0tIDZiZDk2WFoxUiszK3hnSWFKdzRq
              RXRPL1gwZUdNVHRHczVrYnRsdWVaUmsKR4ezzsPiv7QWWLGW/V0rFpILDDZI7p8M
              Wq980iZSVZZHDubUKn41i99zIKsUJhyl3f7S5lCzEYHxKaRoSj/WIA==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-25T19:34:37Z"
    mac: ENC[AES256_GCM,data:3Wnhx+iWFOM4X9kV8MUTZJbAshFhRhHp+TGpbA027EhmE78V4Eg3mT2isosmj4A9jJ3s+9QOR+bdZPBtuJ8jAvXrNDY/BKyDVCdmR3PVHDfs+lG4C4M9WL921U0eNQ5LNft0MFym/ugr+nU+DQ89DlRWsdETe5vZBcN0Ck/aLiw=,iv:q7JcOQdCV8QsqhnFqWQiKTdML8uPRdYYqxKrGzlq2e8=,tag:zWQOLVtW1GCoyu15WzelVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
