---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: bazarr
spec:
  sourcePVC: config-bazarr-0
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: bazarr-volsync
    moverSecurityContext:
      runAsUser: 911
      runAsGroup: 911
      fsGroup: 911
    retain:
      hourly: 24
      daily: 7
      weekly: 5
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: bazarr-dst
spec:
  trigger:
    manual: restore-once
  restic:
    copyMethod: Snapshot
    repository: bazarr-volsync
    accessModes: ["ReadWriteOnce"]
    capacity: 1Gi
    moverSecurityContext:
      runAsUser: 911
      runAsGroup: 911
      fsGroup: 911
