---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
spec:
  targetNamespace: external-secrets
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: prometheus-operator-crds
    - name: cert-manager
  path: ./kubernetes/apps/external-secrets/external-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
spec:
  targetNamespace: external-secrets
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: external-secrets
  path: ./kubernetes/apps/external-secrets/external-secrets/stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
