---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        TUNNEL_TOKEN: "{{ .CLOUDFLARE_TUNNEL_SECRET }}"
  data:
    - secretKey: CLOUDFLARE_TUNNEL_SECRET
      remoteRef:
        key: CLOUDFLARE_TUNNEL_SECRET
