---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.giantswarm.io/silence_v1alpha1.json
apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Silence
metadata:
  name: ceph-node-diskspace-warning
spec:
  matchers:
    - name: alertname
      value: CephNodeDiskspaceWarning
      isRegex: false
    - name: device
      value: /dev/sd.*
      isRegex: true
