---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: cross-seed
    template:
      data:
        config.js: |
          "use strict";

          module.exports = {
            action: "inject",
            apiKey: "{{ .CROSS_SEED_API_KEY }}",
            delay: 30,
            duplicateCategories: true,
            flatLinking: false,
            linkCategory: "cross-seed",
            linkDirs: [
              "/data/downloads/complete/cross-seed"
            ],
            linkType: "hardlink",
            outputDir: "/config",
            qbittorrentUrl: "http://{{ .QBITTORRENT_USERNAME }}:{{ .QBITTORRENT_PASSWORD }}@qbittorrent.default.svc.cluster.local",
            useClientTorrents: true,
            torznab: [
              4, // TorrentLeech
              5  // HD-Torrents
            ].map(i => `http://prowlarr.default.svc.cluster.local/${i}/api?apikey={{ .PROWLARR_KEY }}`) 
          };
  data:
    - secretKey: CROSS_SEED_API_KEY
      remoteRef:
        key: CROSS_SEED_API_KEY
    - secretKey: PROWLARR_KEY
      remoteRef:
        key: PROWLARR_KEY
    - secretKey: QBITTORRENT_USERNAME
      remoteRef:
        key: QBITTORRENT_USERNAME
    - secretKey: QBITTORRENT_PASSWORD
      remoteRef:
        key: QBITTORRENT_PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed-volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: cross-seed-volsync
    template:
      data:
        RESTIC_REPOSITORY: "{{ .VOLSYNC_RESTIC_REPOSITORY }}/cross-seed"
        RESTIC_PASSWORD: "{{ .VOLSYNC_RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .VOLSYNC_AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .VOLSYNC_AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: VOLSYNC_RESTIC_REPOSITORY
      remoteRef:
        key: VOLSYNC_RESTIC_REPOSITORY
    - secretKey: VOLSYNC_RESTIC_PASSWORD
      remoteRef:
        key: VOLSYNC_RESTIC_PASSWORD
    - secretKey: VOLSYNC_AWS_ACCESS_KEY_ID
      remoteRef:
        key: VOLSYNC_AWS_ACCESS_KEY_ID
    - secretKey: VOLSYNC_AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: VOLSYNC_AWS_SECRET_ACCESS_KEY
