---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        config.js: |
          "use strict";

          module.exports = {
            action: "inject",
            apiKey: "{{ .CROSS_SEED_API_KEY }}",
            dataDirs: [
              "/data/downloads/manual",
              "/data/downloads/autobrr"
            ],
            delay: 30,
            flatLinking: false,
            fuzzySizeThreshold: 0.1,
            includeSingleEpisodes: false,
            linkCategory: "cross-seed",
            linkDirs: [
              "/data/downloads/cross-seed"
            ],
            linkType: "hardlink",
            matchMode: "partial",
            maxDataDepth: 3,
            outputDir: null,
            radarr: [
              "http://radarr.default.svc.cluster.local/?apikey={{ .RADARR_KEY }}"
            ],
            seasonFromEpisodes: 1,
            skipRecheck: true,
            sonarr: [
              "http://sonarr.default.svc.cluster.local/?apikey={{ .SONARR_KEY }}"
            ],
            torrentClients: [
              "qbittorrent:http://{{ .QBITTORRENT_USERNAME }}:{{ .QBITTORRENT_PASSWORD }}@qbittorrent.default.svc.cluster.local"
            ],
            torznab: [
              "http://prowlarr.default.svc.cluster.local/4/api?apikey={{ .PROWLARR_KEY }}", // TL
              "http://prowlarr.default.svc.cluster.local/5/api?apikey={{ .PROWLARR_KEY }}"  // HDT
            ],
            useClientTorrents: true
          };
  data:
    - secretKey: CROSS_SEED_API_KEY
      remoteRef:
        key: CROSS_SEED_API_KEY
    - secretKey: RADARR_KEY
      remoteRef:
        key: RADARR_KEY
    - secretKey: SONARR_KEY
      remoteRef:
        key: SONARR_KEY
    - secretKey: PROWLARR_KEY
      remoteRef:
        key: PROWLARR_KEY
    - secretKey: QBITTORRENT_USERNAME
      remoteRef:
        key: QBITTORRENT_USERNAME
    - secretKey: QBITTORRENT_PASSWORD
      remoteRef:
        key: QBITTORRENT_PASSWORD
