---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  cluster: .taskfiles/cluster
  kubernetes: .taskfiles/kubernetes
  volsync: .taskfiles/volsync

tasks:
  default:
    cmd: task --list
    silent: true
