---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  bootstrap: .taskfiles/bootstrap
  flux: .taskfiles/flux
  kubernetes: .taskfiles/kubernetes
  terraform: .taskfiles/terraform

tasks:
  default:
    cmd: task --list
    silent: true
