---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/apps.emqx.io/emqx_v2beta1.json
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: public.ecr.aws/emqx/emqx:5.8.6
  config:
    data: |
      api_key.bootstrap_file = "/opt/emqx/etc/api_keys.txt"
  coreTemplate:
    spec:
      replicas: 3
      envFrom:
        - secretRef:
            name: emqx-admin-password
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "apps.emqx.io/instance"
                    operator: In
                    values:
                      - emqx
              topologyKey: "kubernetes.io/hostname"
      extraVolumes:
        - name: emqx-api-keys
          secret:
            secretName: emqx-api-keys
      extraVolumeMounts:
        - name: emqx-api-keys
          mountPath: /opt/emqx/etc/api_keys.txt
          subPath: api_keys.txt
          readOnly: true
