---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-api-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: emqx-api-keys
    template:
      engineVersion: v2
      data:
        api_keys.txt: |
          {{ .EMQX_EXPORTER_API_KEY }}:{{ .EMQX_EXPORTER_API_SECRET }}
  data:
    - secretKey: EMQX_EXPORTER_API_KEY
      remoteRef:
        key: EMQX_EXPORTER_API_KEY
    - secretKey: EMQX_EXPORTER_API_SECRET
      remoteRef:
        key: EMQX_EXPORTER_API_SECRET
