---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-admin-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: emqx-admin-password
    template:
      engineVersion: v2
      data:
        EMQX_DASHBOARD__DEFAULT_PASSWORD: "{{ .EMQX_DASHBOARD__DEFAULT_PASSWORD }}"
  data:
    - secretKey: EMQX_DASHBOARD__DEFAULT_PASSWORD
      remoteRef:
        key: EMQX_DASHBOARD__DEFAULT_PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-bootstrap-api-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: emqx-bootstrap-api-keys
    template:
      engineVersion: v2
      data:
        emqx-exporter-api-key: "{{ .EMQX_EXPORTER_API_KEY }}"
        emqx-exporter-api-secret: "{{ .EMQX_EXPORTER_API_SECRET }}"
  data:
    - secretKey: EMQX_EXPORTER_API_KEY
      remoteRef:
        key: EMQX_EXPORTER_API_KEY
    - secretKey: EMQX_EXPORTER_API_SECRET
      remoteRef:
        key: EMQX_EXPORTER_API_SECRET
