---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      minio:
        containers:
          app:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2025-03-12T18-04-18Z
            envFrom:
              - secretRef:
                  name: minio-env-configuration
            args: ["server", "/data", "--console-address", ":9090"]

    # TODO: nfs temp fix
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: minio
        ports:
          http:
            port: 9090
          s3:
            port: 9000

    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 8m
        className: nginx
        hosts:
          - host: minio.nasenov.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: s3.nasenov.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: s3

    persistence:
      config:
        type: nfs
        server: 192.168.0.15
        path: /mnt/tank/minio
        globalMounts:
          - path: /data
