---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      minio:
        # TODO: nfs temp fix
        pod:
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2025-03-12T18-04-18Z
            args: ["server", "/data", "--console-address", ":9090"]
            envFrom:
              - secretRef:
                  name: minio-env-configuration

    service:
      app:
        controller: minio
        ports:
          http:
            port: 9090
          s3:
            port: 9000

    route:
      app:
        hostnames:
          - minio.nasenov.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: minio
                port: 9090
      s3:
        hostnames:
          - s3.nasenov.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: minio
                port: 9000

    persistence:
      config:
        type: nfs
        server: 192.168.0.15
        path: /mnt/tank/minio
        globalMounts:
          - path: /data
