---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autobrr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      autobrr:
        type: statefulset

        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              accessMode: ReadWriteOnce
              dataSourceRef:
                apiGroup: volsync.backube
                kind: ReplicationDestination
                name: autobrr-dst
              size: 1Gi
              storageClass: ceph-block

        containers:
          app:
            image:
              repository: ghcr.io/autobrr/autobrr
              tag: v1.60.0@sha256:5f95def0aa664e653c5de820f27661357a5c77a8eef0dd7fa204efedfb7d0e45
            env:
              AUTOBRR__CHECK_FOR_UPDATES: "false"
              AUTOBRR__HOST: 0.0.0.0
              AUTOBRR__PORT: &port 80
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 256Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: autobrr
        ports:
          http:
            port: *port

    ingress:
      app:
        className: nginx
        hosts:
          - host: autobrr.nasenov.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - hosts:
              - autobrr.nasenov.dev
