---
- hosts: all
  roles:
    - prometheus.prometheus.node_exporter
  vars:
    node_exporter_version: 1.9.1
    node_exporter_system_user: node_exporter
    node_exporter_system_group: node_exporter
