---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: n8n
    template:
      engineVersion: v2
      data:
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: N8N_ENCRYPTION_KEY
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-xiaomi-body-compositon-workflow
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: postgres-secrets-store
  target:
    name: n8n-xiaomi-body-compositon-workflow
    template:
      engineVersion: v2
      data:
        XIAOMI_BODY_COMPOSITON_POSTGRES_HOST: "{{ .pgbouncer_host }}"
        XIAOMI_BODY_COMPOSITON_POSTGRES_PORT: "{{ .pgbouncer_port }}"
        XIAOMI_BODY_COMPOSITON_POSTGRES_DATABASE: "{{ .dbname }}"
        XIAOMI_BODY_COMPOSITON_POSTGRES_USER: "{{ .user }}"
        XIAOMI_BODY_COMPOSITON_POSTGRES_PASSWORD: "{{ .password }}"
        XIAOMI_BODY_COMPOSITON_POSTGRES_IGNORE_SSL: "true"
        XIAOMI_BODY_COMPOSITON_POSTGRES_MAX_OPEN_CONN: "4"
  dataFrom:
    - extract:
        key: postgres-pguser-fitness
      rewrite:
        - regexp:
            source: "-"
            target: "_"
