---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      n8n:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/n8n-io/n8n
              tag: 1.95.2@sha256:4af5586ec8d566430ec48f175ae96810f4818d13c733dac067b020c510b8cadf
            env:
              GENERIC_TIMEZONE: Europe/Sofia
              N8N_PROTOCOL: https
              N8N_HOST: &hostName n8n.nasenov.dev
              N8N_PORT: &port 5678
              N8N_DIAGNOSTICS_ENABLED: "false"
              N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
              N8N_METRICS: "true"
              QUEUE_HEALTH_CHECK_ACTIVE: "true"
            envFrom:
              - secretRef:
                  name: n8n
              - secretRef:
                  name: n8n-xiaomi-body-compositon-workflow
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz/readiness
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: n8n
        ports:
          http:
            port: *port

    serviceMonitor:
      app:
        serviceName: n8n
        endpoints:
          - port: http

    route:
      app:
        hostnames:
          - *hostName
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        existingClaim: n8n
        globalMounts:
          - path: /home/node/.n8n
