---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: alloy
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    alloy:
      configMap:
        create: false
        name: alloy
        key: config.alloy
      # securityContext:
      #   runAsUser: 473
      #   runAsGroup: 473

    controller:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule

    serviceMonitor:
      enabled: true

    extraObjects:
      - apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: alloy
        spec:
          hostnames:
            - alloy.nasenov.dev
          parentRefs:
            - name: internal
              namespace: kube-system
              sectionName: https
          rules:
            - backendRefs:
                - name: alloy
                  namespace: monitoring
                  port: 12345
