---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugin
spec:
  targetNamespace: kube-system
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: node-feature-discovery
      namespace: kube-system
  path: ./kubernetes/apps/kube-system/intel-device-plugin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
