---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-operator
spec:
  targetNamespace: database
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  path: ./kubernetes/apps/database/emqx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-cluster
spec:
  targetNamespace: database
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: emqx-operator
      namespace: database
    - name: prometheus-operator-crds
      namespace: monitoring
  path: ./kubernetes/apps/database/emqx/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
