---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: silence-operator
spec:
  targetNamespace: monitoring
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  path: ./kubernetes/apps/monitoring/silence-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: silence-operator-silences
spec:
  targetNamespace: monitoring
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: silence-operator
      namespace: monitoring
  path: ./kubernetes/apps/monitoring/silence-operator/silences
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
