---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crunchy-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: crunchy-postgres-secret
    template:
      engineVersion: v2
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .MINIO_ROOT_USER }}
          repo1-s3-key-secret={{ .MINIO_ROOT_PASSWORD }}
          repo1-cipher-pass={{ .POSTGRESQL_BACKUP_ENCRYPTION_CIPHER_PASS }}
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: MINIO_ROOT_USER
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: MINIO_ROOT_PASSWORD
    - secretKey: POSTGRESQL_BACKUP_ENCRYPTION_CIPHER_PASS
      remoteRef:
        key: POSTGRESQL_BACKUP_ENCRYPTION_CIPHER_PASS
