---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: pgadmin
spec:
  users:
    - username: pgadmin@nasenov.dev
      role: Administrator
      passwordRef:
        name: pgadmin
        key: pgadmin-password
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  serverGroups:
    - name: postgres
      postgresClusterName: postgres
