---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name postgres
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  postgresVersion: 17

  instances:
    - name: postgres
      replicas: 2
      minAvailable: 1
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 16Gi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: *name
                  postgres-operator.crunchydata.com/instance-set: postgres

  service:
    type: LoadBalancer
    metadata:
      annotations:
        lbipam.cilium.io/ips: 192.168.0.42

  backups:
    pgbackrest:
      configuration: &backupConfig
        - secret:
            name: crunchy-postgres-secret
      global: &backupGlobal
        compress-type: "bz2"
        compress-level: "9"
        # Minio
        repo1-bundle: "y"
        repo1-block: "y"
        repo1-cipher-type: aes-256-cbc
        repo1-s3-uri-style: path
        repo1-path: /pgbackrest/database/postgres/repo1
        repo1-retention-full: "30" # days
        repo1-retention-full-type: time
        repo1-storage-verify-tls: "n"
        # R2
        repo2-block: "y"
        repo2-bundle: "y"
        repo2-cipher-type: aes-256-cbc
        repo2-s3-uri-style: path
        repo2-path: /pgbackrest/database/postgres/repo2
        repo2-retention-full: "7" # days
        repo2-retention-full-type: time
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          s3: &backupS3
            bucket: postgres
            endpoint: truenas.nasenov.dev:9000
            region: eu-central-1
          schedules:
            full: "0 1 * * 0" # Sunday at 01:00
            differential: "0 1 * * 1-6" # Mon-Sat at 01:00
            incremental: "0 2-23 * * *" # Every hour except 01:00
        - name: repo2
          s3:
            bucket: postgres
            endpoint: ${POSTGRESQL_R2_ENDPOINT}
            region: auto
          schedules:
            full: "0 2 * * 0" # Sunday at 02:00
            incremental: "0 2 * * 1-6" # Mon-Sat at 02:00

  dataSource:
    pgbackrest:
      stanza: db
      configuration: *backupConfig
      global: *backupGlobal
      repo:
        name: repo1
        s3: *backupS3

  proxy:
    pgBouncer:
      config:
        global:
          log_connections: "0"
          log_disconnections: "0"
      replicas: 2
      minAvailable: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: *name
                  postgres-operator.crunchydata.com/role: pgbouncer

  users:
    # Superuser
    - name: postgres
      # databases:
      #   - postgres
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    # Applications
    - name: grafana
      databases:
        - grafana
      password:
        type: AlphaNumeric
    - name: fitness
      databases:
        - fitness
      password:
        type: AlphaNumeric

  patroni:
    dynamicConfiguration:
      failsafe_mode: true
      synchronous_mode: true
      postgresql:
        parameters:
          synchronous_commit: "on"

  monitoring:
    pgmonitor:
      exporter: {}
