---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: grafana-admin
    template:
      engineVersion: v2
      data:
        admin-user: "{{ .GRAFANA_ADMIN_USER }}"
        admin-password: "{{ .GRAFANA_ADMIN_PASSWORD }}"
  data:
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: GRAFANA_ADMIN_USER
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: GRAFANA_ADMIN_PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-postgres-configuration
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: postgres-secrets-store
  target:
    name: grafana-postgres-configuration
    template:
      engineVersion: v2
      data:
        GF_DATABASE_TYPE: postgres
        GF_DATABASE_HOST: "{{ .host }}:{{ .port }}"
        GF_DATABASE_NAME: "{{ .dbname }}"
        GF_DATABASE_USER: "{{ .user }}"
        GF_DATABASE_PASSWORD: "{{ .password }}"
        GF_DATABASE_SSL_MODE: require
        DATABASE_SSL_MODE: disable
  dataFrom:
    - extract:
        key: postgres-pguser-grafana
      rewrite:
        - regexp:
            source: "-"
            target: "_"
