---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      engineVersion: v2
      data:
        admin-user: "{{ .GRAFANA_ADMIN_USER }}"
        admin-password: "{{ .GRAFANA_ADMIN_PASSWORD }}"
  data:
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: GRAFANA_ADMIN_USER
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: GRAFANA_ADMIN_PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-postgres-configuration
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: postgres-secrets-store
  target:
    template:
      engineVersion: v2
      data:
        GF_DATABASE_TYPE: postgres
        GF_DATABASE_HOST: "{{ .pgbouncer_host }}:{{ .pgbouncer_port }}"
        GF_DATABASE_NAME: "{{ .dbname }}"
        GF_DATABASE_USER: "{{ .user }}"
        GF_DATABASE_PASSWORD: "{{ .password }}"
        GF_DATABASE_MAX_OPEN_CONN: "4"
        GF_DATABASE_SSL_MODE: require
  dataFrom:
    - extract:
        key: postgres-pguser-grafana
      rewrite:
        - regexp:
            source: "-"
            target: "_"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-postgres-datasource-configuration
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: postgres-secrets-store
  target:
    template:
      engineVersion: v2
      data:
        POSTGRES_DATASOURCE_URL: "{{ .pgbouncer_host }}:{{ .pgbouncer_port }}"
        POSTGRES_DATASOURCE_DATABASE: "{{ .dbname }}"
        POSTGRES_DATASOURCE_USER: "{{ .user }}"
        POSTGRES_DATASOURCE_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: postgres-pguser-fitness
      rewrite:
        - regexp:
            source: "-"
            target: "_"
