---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
spec:
  storageClassName: "${VOLSYNC_STORAGECLASS:=ceph-block}"
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: "${APP}-dst"
  accessModes:
    - "${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:=1Gi}"
