---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crunchy-postgres-operator
  namespace: flux-system
spec:
  targetNamespace: database
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  path: ./kubernetes/apps/database/crunchy-postgres-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crunchy-postgres-operator-cluster
  namespace: flux-system
spec:
  targetNamespace: database
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: crunchy-postgres-operator
    - name: external-secrets-stores
    - name: prometheus-operator-crds
  path: ./kubernetes/apps/database/crunchy-postgres-operator/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
