---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbtools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        QBITTORRENT_USER: "{{ .QBITTORRENT_USERNAME }}"
        QBITTORRENT_PASS: "{{ .QBITTORRENT_PASSWORD }}"
  data:
    - secretKey: QBITTORRENT_USERNAME
      remoteRef:
        key: QBITTORRENT_USERNAME
    - secretKey: QBITTORRENT_PASSWORD
      remoteRef:
        key: QBITTORRENT_PASSWORD
