---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbtools
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: default
  values:
    controllers:
      tagging:
        type: cronjob
        cronjob: &cronJobSpec
          schedule: 0 * * * *
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 3600
        initContainers:
          tag: &container
            image:
              repository: ghcr.io/buroa/qbtools
              tag: v0.19.15@sha256:4145020bab12b2ed892f548c2812c4979793def80dce5f907e49640329e54933
            env:
              QBITTORRENT_HOST: qbittorrent.default.svc.cluster.local
              QBITTORRENT_PORT: 80
            envFrom:
              - secretRef:
                  name: qbtools
            args: [
              "tagging",
              "--added-on",
              "--expired",
              "--last-activity",
              "--sites",
              "--unregistered"
            ]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256M
        containers:
          unregistered:
            <<: *container
            args: [
              "prune",
              "--exclude-category", "manual",
              "--exclude-tag", "added:1d",
              "--include-tag", "unregistered",
              "--with-data",
              # "--dry-run"
            ]
          expired:
            <<: *container
            args: [
              "prune",
              "--exclude-category", "manual",
              "--exclude-tag", "added:1d",
              "--include-tag", "expired",
              "--with-data",
              "--dry-run"
            ]
        pod:
          restartPolicy: Never
      
      orphaned:
        type: cronjob
        cronjob:
          <<: *cronJobSpec
          schedule: 0 0 * * 0
        containers:
          app:
            <<: *container
            args: [
              "orphaned",
              "--exclude-pattern", "*_unpackerred*",
              "--exclude-pattern", "*/manual/*",
              # "--dry-run"
            ]
        pod:
          restartPolicy: Never
      
      reannounce:
        containers:
          app:
            <<: *container
            args: [
              "reannounce",
              "--process-seeding"
            ]
    
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      secret-file:
        type: secret
        name: qbtools-config
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true    
      media:
        enabled: true
        type: nfs
        server: 192.168.0.15
        path: /mnt/tank/media
        advancedMounts:
          orphaned:
            app:
              - path: /data/downloads
                subPath: downloads
