---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silence-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: silence-operator
      version: 0.16.1
      sourceRef:
        kind: HelmRepository
        name: silence-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      registry: quay.io
      name: giantswarm/silence-operator
      tag: 0.16.1

    alertmanagerAddress: http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093

    networkPolicy:
      enabled: false
