---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  apply:
    dir: "{{.ROOT_DIR}}/terraform/kubernetes"
    cmd: terraform apply

  bootstrap:
    dir: "{{.ROOT_DIR}}/terraform/bootstrap"
    cmds:
      - kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/experimental-install.yaml
      - terraform apply

  sync:
    dir: "{{.ROOT_DIR}}/terraform/proxmox"
    cmd: terraform apply

  destroy:
    dir: "{{.ROOT_DIR}}/terraform/kubernetes"
    cmd: terraform destroy

  output:
    dir: "{{.ROOT_DIR}}/terraform/kubernetes"
    cmds:
      - terraform output -raw kubeconfig > ~/.kube/config
      - chmod 600 ~/.kube/config
      - terraform output -raw talosconfig > ~/.talos/config
      - chmod 600 ~/.talos/config
