---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-certificates
spec:
  targetNamespace: networking
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/apps/networking/ingress-nginx/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
spec:
  targetNamespace: networking
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: ingress-nginx-certificates
      namespace: networking
    - name: prometheus-operator-crds
      namespace: monitoring
  path: ./kubernetes/apps/networking/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
