---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator
spec:
  targetNamespace: flux-system
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  path: ./kubernetes/apps/flux-system/flux-operator/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-instance
spec:
  targetNamespace: flux-system
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: flux-operator
      namespace: flux-system
  path: ./kubernetes/apps/flux-system/flux-operator/instance
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
