---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: emqx-operator
      version: 2.2.28
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/emqx/emqx-operator
