---
services:
  pihole:
    container_name: pihole
    image: ghcr.io/pi-hole/pihole:2025.05.1
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: Europe/Sofia
      FTLCONF_dns_listeningMode: all
      WEBPASSWORD_FILE: pi_hole_admin_password
    secrets:
      - pi_hole_admin_password
    volumes:
      - pihole:/etc/pihole

secrets:
  pi_hole_admin_password:
    file: pi_hole_admin_password

volumes:
  pihole:
