---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: stakater
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    reloader:
      reloadStrategy: annotations
