services:
  smartctl-exporter:
    image: quay.io/prometheuscommunity/smartctl-exporter:v0.14.0
    command:
      - '--smartctl.device-exclude=sda'
    ports:
      - "9633:9633"
    privileged: true
    restart: always
    user: root
