---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      config:
        enable-real-ip: "true"
        use-forwarded-headers: "true"
      service:
        annotations:
          lbipam.cilium.io/ips: 192.168.0.40
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      extraArgs:
        default-ssl-certificate: networking/nasenov-dev-tls
