---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: pihole-dns
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: pihole-dns
    image:
      repository: registry.k8s.io/external-dns/external-dns
      tag: v0.17.0@sha256:85eba2727b410c8f8093d641a4b1a29671878db94d525a70a4108d10ba8eef5f
    provider:
      name: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-dns
            key: EXTERNAL_DNS_PIHOLE_PASSWORD
    extraArgs:
      - --pihole-api-version=6
      - --pihole-server=http://192.168.0.53
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - gateway-httproute
      - crd
    registry: noop
    domainFilters:
      - nasenov.dev
    serviceMonitor:
      enabled: true
