---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: pihole-dns
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: pihole-dns
    provider:
      name: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-dns
            key: EXTERNAL_DNS_PIHOLE_PASSWORD
    extraArgs:
      - --pihole-api-version=6
      - --pihole-server=http://192.168.0.53
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - gateway-httproute
    registry: noop
    domainFilters:
      - nasenov.dev
    serviceMonitor:
      enabled: true
