---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  upgrade-node:
    desc: Upgrade Talos on a single node [IP=required]
    cmds:
      - task: down
      - talosctl --nodes {{.IP}} upgrade --image factory.talos.dev/installer/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30:v1.9.4
      - talosctl --nodes {{.IP}} health --wait-timeout=10m --server=false
      - task: up
    requires:
      vars: [IP]
    preconditions:
      - which jq talosctl

  upgrade-k8s:
    cmds:
      - talosctl --nodes {{.TALOS_CONTROLLER}} upgrade-k8s --to 1.32.0
    vars:
      TALOS_CONTROLLER:
        sh: talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1

  upgrade-cluster:
    desc: Upgrade Talos across the whole cluster
    cmds:
      - for: { var: IP_ADDRS }
        task: upgrade-node
        vars:
          IP: '{{.ITEM}}'
    vars:
      IP_ADDRS:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(" ")'
    preconditions:
      - which jq talosctl

  down:
    internal: true
    cmds:
      - until kubectl wait cephcluster --for=jsonpath=.status.ceph.health=HEALTH_OK --timeout=10m --all --all-namespaces &>/dev/null; do sleep 5; done
      - until kubectl wait jobs --all --all-namespaces --for=condition=complete --timeout=5m &>/dev/null; do sleep 5; done
    preconditions:
      - which kubectl

  up:
    internal: true
    cmds:
      - until kubectl wait cephcluster --for=jsonpath=.status.ceph.health=HEALTH_OK --timeout=10m --all --all-namespaces &>/dev/null; do sleep 5; done
      - until kubectl wait jobs --all --all-namespaces --for=condition=complete --timeout=5m &>/dev/null; do sleep 5; done
    preconditions:
      - which kubectl
