---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smartctl-exporter
spec:
  interval: 10m0s
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: smartctl-exporter

    config:
      devices:
        - /dev/nvme0n1

    serviceMonitor:
      enabled: true

    prometheusRules:
      enabled: true

    nodeSelector:
      # NVMe label
      feature.node.kubernetes.io/pci-0108.present: "true"
