# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kubelet-csr-approver
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    providerRegex: ^k8s-\d+$
    bypassDnsResolution: true
    metrics:
      enable: true
      serviceMonitor:
        enabled: true
