# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
spec:
  interval: 30m
  chart:
    spec:
      chart: kubelet-csr-approver
      version: 1.2.6
      sourceRef:
        kind: HelmRepository
        name: postfinance
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    providerRegex: ^k8s-\d+$
    bypassDnsResolution: true
    metrics:
      enable: true
      serviceMonitor:
        enabled: true
