---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
spec:
  interval: 30m
  chart:
    spec:
      chart: spegel
      version: v0.0.30
      sourceRef:
        kind: HelmRepository
        name: spegel
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    spegel:
      appendMirrors: true
      containerdSock: /run/containerd/containerd.sock
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
    service:
      registry:
        hostPort: 29999      
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
