---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      radarr:
        type: statefulset

        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              accessMode: ReadWriteOnce
              dataSourceRef:
                apiGroup: volsync.backube
                kind: ReplicationDestination
                name: radarr-dst
              size: 1Gi
              storageClass: ceph-block

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 5.22.2.9862@sha256:9f24da505e2ba09957355a2b638660af2325e9861efb8b77583ca71fa6790789
            env:
              TZ: Europe/Sofia
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 256Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 911
        runAsGroup: 911
        fsGroup: 911
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: radarr
        ports:
          http:
            port: 80
            targetPort: 7878

    route:
      app:
        hostnames:
          - radarr.nasenov.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: radarr
                port: 80

    persistence:
      media:
        enabled: true
        type: nfs
        server: 192.168.0.15
        path: /mnt/tank/media
        globalMounts:
          - path: /data
