# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 10m0s
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 69.2.4
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      retries: 3
  values:
    cleanPrometheusOperatorObjectNames: true

    crds:
      enabled: false

    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.nasenov.dev
        tls:
          - hosts:
              - prometheus.nasenov.dev

      prometheusSpec:
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        retention: 3d
        retentionSize: 20GB
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: openebs-hostpath
              resources:
                requests:
                  storage: 25Gi

    alertmanager:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - alertmanager.nasenov.dev
        tls:
          - hosts:
              - alertmanager.nasenov.dev

      alertmanagerSpec:
        useExistingSecret: true
        configSecret: alertmanager-configuration
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: openebs-hostpath
              resources:
                requests:
                  storage: 1Gi

    grafana:
      enabled: false
      forceDeployDashboards: true

    nodeExporter:
      enabled: false

    kubeStateMetrics:
      enabled: false

    kubeApiServer:
      service:
        selector:
          k8s-app: kube-apiserver

    kubeControllerManager:
      service:
        selector:
          k8s-app: kube-controller-manager

    kubeEtcd:
      service:
        selector:
          k8s-app: kube-controller-manager

    kubeScheduler:
      service:
        selector:
          k8s-app: kube-scheduler

    kubeProxy:
      enabled: false
