# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      retries: 3
  values:
    cleanPrometheusOperatorObjectNames: true

    crds:
      enabled: false

    prometheus:
      route:
        main:
          enabled: true
          hostnames:
            - prometheus.nasenov.dev
          parentRefs:
            - name: internal
              namespace: kube-system
              sectionName: https

      prometheusSpec:
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        retention: 3d
        retentionSize: 20GB
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: openebs-hostpath
              resources:
                requests:
                  storage: 25Gi
        additionalScrapeConfigs:
          - job_name: pve-node-exporter
            static_configs:
              - targets:
                  - pve.nasenov.dev:9100

    alertmanager:
      route:
        main:
          enabled: true
          hostnames:
            - alertmanager.nasenov.dev
          parentRefs:
            - name: internal
              namespace: kube-system
              sectionName: https

      alertmanagerSpec:
        useExistingSecret: true
        configSecret: alertmanager-configuration
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: openebs-hostpath
              resources:
                requests:
                  storage: 1Gi

    grafana:
      enabled: false
      forceDeployDashboards: true

    nodeExporter:
      enabled: false

    kubeStateMetrics:
      enabled: false

    kubeApiServer:
      service:
        selector:
          k8s-app: kube-apiserver

    kubeControllerManager:
      service:
        selector:
          k8s-app: kube-controller-manager

    kubeEtcd:
      service:
        selector:
          k8s-app: kube-controller-manager

    kubeScheduler:
      service:
        selector:
          k8s-app: kube-scheduler

    kubeProxy:
      enabled: false
