---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        config.yaml: |
          metrics:
            target: emqx-dashboard.database.svc.cluster.local:18083
            api_key: {{ .EMQX_EXPORTER_API_KEY }}
            api_secret: {{ .EMQX_EXPORTER_API_SECRET }}
          probes:
            - target: emqx-listeners.database.svc.cluster.local:1883
  data:
    - secretKey: EMQX_EXPORTER_API_KEY
      remoteRef:
        key: EMQX_EXPORTER_API_KEY
    - secretKey: EMQX_EXPORTER_API_SECRET
      remoteRef:
        key: EMQX_EXPORTER_API_SECRET
