---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      jellyseerr:
        containers:
          app:
            image:
              repository: ghcr.io/fallenbagel/jellyseerr
              tag: 2.5.2
            env:
              TZ: Europe/Sofia
              LOG_LEVEL: info
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: 5055
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi

    service:
      app:
        controller: jellyseerr
        ports:
          http:
            port: 80
            targetPort: 5055

    route:
      app:
        hostnames:
          - jellyseerr.nasenov.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: jellyseerr
                port: 80

    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: ceph-block
        dataSourceRef:
          apiGroup: volsync.backube
          kind: ReplicationDestination
          name: jellyseerr-dst
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /app/config
      config-cache:
        type: emptyDir
        globalMounts:
          - path: /app/config/cache
      config-logs:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
