---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.2
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      jellyseerr:
        type: statefulset

        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /app/config
              accessMode: ReadWriteOnce
              dataSourceRef:
                apiGroup: volsync.backube
                kind: ReplicationDestination
                name: jellyseerr-dst
              size: 1Gi
              storageClass: ceph-block

        containers:
          app:
            image:
              repository: fallenbagel/jellyseerr
              tag: 2.3.0
            env:
              TZ: Europe/Sofia
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 512Mi

    service:
      app:
        controller: jellyseerr
        ports:
          http:
            port: 80
            targetPort: 5055

    ingress:
      app:
        className: nginx
        hosts:
          - host: jellyseerr.nasenov.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - hosts:
              - jellyseerr.nasenov.dev
