---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jellyseerr
spec:
  sourcePVC: jellyseerr-config
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: jellyseerr-volsync
    retain:
      hourly: 24
      daily: 7
      weekly: 5
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: jellyseerr-dst
spec:
  trigger:
    manual: restore-once
  restic:
    copyMethod: Snapshot
    repository: jellyseerr-volsync
    accessModes: ["ReadWriteOnce"]
    capacity: 1Gi
