---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-csr-approver
  namespace: flux-system
spec:
  targetNamespace: kube-system
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: prometheus-operator-crds
  path: ./kubernetes/apps/kube-system/kubelet-csr-approver/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
