---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-remote"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        RESTIC_REPOSITORY: "{{ .VOLSYNC_R2_ENDPOINT }}/${APP}"
        RESTIC_PASSWORD: "{{ .VOLSYNC_RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .VOLSYNC_R2_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .VOLSYNC_R2_ACCESS_KEY_SECRET }}"
  data:
    - secretKey: VOLSYNC_R2_ENDPOINT
      remoteRef:
        key: 93232fe3-d6cb-4e66-b958-b2d6006676ab
    - secretKey: VOLSYNC_RESTIC_PASSWORD
      remoteRef:
        key: ff1f55f8-b6a8-4b3d-8ad6-b27c0153b42b
    - secretKey: VOLSYNC_R2_ACCESS_KEY
      remoteRef:
        key: 67fb84ac-df20-45e3-bfa4-b2d60065ff36
    - secretKey: VOLSYNC_R2_ACCESS_KEY_SECRET
      remoteRef:
        key: c2a1fe87-82fe-4167-bc6f-b2d600661896
