---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}-remote"
spec:
  sourcePVC: "${APP}"
  trigger:
    schedule: "30 0 * * *"
  restic:
    copyMethod: "${VOLSYNC_COPYMETHOD:=Snapshot}"
    pruneIntervalDays: 14
    repository: "${APP}-volsync-remote"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=ceph-block}"
    cacheAccessModes:
      - "${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=1Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:=ceph-block}"
    accessModes:
      - "${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}"
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
    retain:
      daily: 7
