---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        RADARR_API_KEY: "{{ .RADARR_KEY }}"
        SONARR_API_KEY: "{{ .SONARR_KEY }}"
  data:
    - secretKey: SONARR_KEY
      remoteRef:
        key: 2018ba36-f54b-4269-aa43-b27f01357eaa
    - secretKey: RADARR_KEY
      remoteRef:
        key: d0491587-c8dc-4e81-a1f7-b27f01353cf5
