---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: recyclarr
    template:
      data:
        RADARR_API_KEY: "{{ .RADARR_KEY }}"
        SONARR_API_KEY: "{{ .SONARR_KEY }}"
  data:
    - secretKey: SONARR_KEY
      remoteRef:
        key: SONARR_KEY
    - secretKey: RADARR_KEY
      remoteRef:
        key: RADARR_KEY
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: recyclarr-volsync
    template:
      data:
        RESTIC_REPOSITORY: "{{ .VOLSYNC_RESTIC_REPOSITORY }}/recyclarr"
        RESTIC_PASSWORD: "{{ .VOLSYNC_RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .VOLSYNC_AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .VOLSYNC_AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: VOLSYNC_RESTIC_REPOSITORY
      remoteRef:
        key: VOLSYNC_RESTIC_REPOSITORY
    - secretKey: VOLSYNC_RESTIC_PASSWORD
      remoteRef:
        key: VOLSYNC_RESTIC_PASSWORD
    - secretKey: VOLSYNC_AWS_ACCESS_KEY_ID
      remoteRef:
        key: VOLSYNC_AWS_ACCESS_KEY_ID
    - secretKey: VOLSYNC_AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: VOLSYNC_AWS_SECRET_ACCESS_KEY
