---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: homepage
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_HOME_ASSISTANT_TOKEN: "{{ .HOMEPAGE_HOME_ASSISTANT_TOKEN }}"
        HOMEPAGE_VAR_GRAFANA_ADMIN_USER: "{{ .GRAFANA_ADMIN_USER }}"
        HOMEPAGE_VAR_GRAFANA_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        HOMEPAGE_VAR_JELLYFIN_KEY: "{{ .HOMEPAGE_JELLYFIN_KEY }}"
        HOMEPAGE_VAR_JELLYSEER_KEY: "{{ .JELLYSEER_KEY }}"
        HOMEPAGE_VAR_RADARR_KEY: "{{ .RADARR_KEY }}"
        HOMEPAGE_VAR_SONARR_KEY: "{{ .SONARR_KEY }}"
        HOMEPAGE_VAR_BAZARR_KEY: "{{ .BAZARR_KEY }}"
        HOMEPAGE_VAR_PROWLARR_KEY: "{{ .PROWLARR_KEY }}"
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: "{{ .QBITTORRENT_USERNAME }}"
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}"
        HOMEPAGE_VAR_AUTOBRR_KEY: "{{ .AUTOBRR_KEY }}"
        HOMEPAGE_VAR_PROXMOX_USERNAME: "{{ .HOMEPAGE_PROXMOX_USERNAME }}"
        HOMEPAGE_VAR_PROXMOX_PASSWORD: "{{ .HOMEPAGE_PROXMOX_PASSWORD }}"
        HOMEPAGE_VAR_TRUENAS_KEY: "{{ .HOMEPAGE_TRUENAS_KEY }}"
  data:
    - secretKey: HOMEPAGE_HOME_ASSISTANT_TOKEN
      remoteRef:
        key: HOMEPAGE_HOME_ASSISTANT_TOKEN
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: GRAFANA_ADMIN_USER
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: GRAFANA_ADMIN_PASSWORD
    - secretKey: HOMEPAGE_JELLYFIN_KEY
      remoteRef:
        key: HOMEPAGE_JELLYFIN_KEY
    - secretKey: JELLYSEER_KEY
      remoteRef:
        key: JELLYSEER_KEY
    - secretKey: RADARR_KEY
      remoteRef:
        key: RADARR_KEY
    - secretKey: SONARR_KEY
      remoteRef:
        key: SONARR_KEY
    - secretKey: BAZARR_KEY
      remoteRef:
        key: BAZARR_KEY
    - secretKey: PROWLARR_KEY
      remoteRef:
        key: PROWLARR_KEY
    - secretKey: QBITTORRENT_USERNAME
      remoteRef:
        key: QBITTORRENT_USERNAME
    - secretKey: QBITTORRENT_PASSWORD
      remoteRef:
        key: QBITTORRENT_PASSWORD
    - secretKey: AUTOBRR_KEY
      remoteRef:
        key: AUTOBRR_KEY
    - secretKey: HOMEPAGE_PROXMOX_USERNAME
      remoteRef:
        key: HOMEPAGE_PROXMOX_USERNAME
    - secretKey: HOMEPAGE_PROXMOX_PASSWORD
      remoteRef:
        key: HOMEPAGE_PROXMOX_PASSWORD
    - secretKey: HOMEPAGE_TRUENAS_KEY
      remoteRef:
        key: HOMEPAGE_TRUENAS_KEY
