# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      enableServiceLinks: true
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      homepage:
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.1.2
            env:
              HOMEPAGE_ALLOWED_HOSTS: homepage.nasenov.dev
            envFrom:
              - secretRef:
                  name: homepage
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi

    service:
      app:
        controller: homepage
        primary: true
        ports:
          http:
            port: 80
            targetPort: 3000

    route:
      app:
        hostnames:
          - homepage.nasenov.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: homepage
                port: 80

    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - path: /app/config
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs

    configMaps:
      config:
        enabled: true
        data:
          bookmarks.yaml: |
            ---
          custom.css: ""
          custom.js: ""
          docker.yaml: |
            ---
          kubernetes.yaml: |
            ---
            mode: disabled
          services.yaml: |
            ---
            - Media:
                - Jellyfin:
                    icon: jellyfin.png
                    href: https://media.nasenov.dev
                    widget:
                      type: jellyfin
                      url: http://jellyfin.default.svc.cluster.local
                      key: {{ "{{" }}HOMEPAGE_VAR_JELLYFIN_KEY{{ "}}" }}
                      enableNowPlaying: false # optional, defaults to true
                      enableBlocks: true # optional, defaults to false
                      fields: ["movies", "series", "episodes"]
                - Jellyseerr:
                    icon: jellyseerr.png
                    href: https://jellyseerr.nasenov.dev
                    widget:
                      type: jellyseerr
                      url: http://jellyseerr.default.svc.cluster.local
                      key: {{ "{{" }}HOMEPAGE_VAR_JELLYSEER_KEY{{ "}}" }}
                      fields: ["pending", "approved", "available"]
                - Radarr:
                    icon: radarr.png
                    href: https://radarr.nasenov.dev
                    widget:
                      type: radarr
                      url: http://radarr.default.svc.cluster.local
                      key: {{ "{{" }}HOMEPAGE_VAR_RADARR_KEY{{ "}}" }}
                      fields: ["wanted", "queued", "movies"]
                - Sonarr:
                    icon: sonarr.png
                    href: https://sonarr.nasenov.dev
                    widget:
                      type: sonarr
                      url: http://sonarr.default.svc.cluster.local
                      key: {{ "{{" }}HOMEPAGE_VAR_SONARR_KEY{{ "}}" }}
                      fields: ["wanted", "queued", "series"]
                - Bazarr:
                    icon: bazarr.png
                    href: https://bazarr.nasenov.dev
                    widget:
                      type: bazarr
                      url: http://bazarr.default.svc.cluster.local
                      key: {{ "{{" }}HOMEPAGE_VAR_BAZARR_KEY{{ "}}" }}
                      fields: ["missingEpisodes", "missingMovies"]
                - Prowlarr:
                    icon: prowlarr.png
                    href: https://prowlarr.nasenov.dev
                    widget:
                      type: prowlarr
                      url: http://prowlarr.default.svc.cluster.local
                      key: {{ "{{" }}HOMEPAGE_VAR_PROWLARR_KEY{{ "}}" }}
                      fields: ["numberOfGrabs", "numberOfQueries"]
                - qBittorrent:
                    icon: qbittorrent.png
                    href: https://qb.nasenov.dev
                    widget:
                      type: qbittorrent
                      url: http://qbittorrent.default.svc.cluster.local
                      username: {{ "{{" }}HOMEPAGE_VAR_QBITTORRENT_USERNAME{{ "}}" }}
                      password: {{ "{{" }}HOMEPAGE_VAR_QBITTORRENT_PASSWORD{{ "}}" }}
                      fields: ["download", "seed", "upload"]
                - Autobrr:
                    icon: autobrr.png
                    href: https://autobrr.nasenov.dev
                    widget:
                      type: autobrr
                      url: http://autobrr.default.svc.cluster.local
                      key:  {{ "{{" }}HOMEPAGE_VAR_AUTOBRR_KEY{{ "}}" }}
                      fields: ["approvedPushes", "rejectedPushes", "filters", "indexers"]

            - Infrastructure:
                - Proxmox:
                    icon: proxmox.png
                    href: https://pve.nasenov.dev:8006
                    widget:
                      type: proxmox
                      url: https://192.168.0.10:8006
                      username: {{ "{{" }}HOMEPAGE_VAR_PROXMOX_USERNAME{{ "}}" }}
                      password: {{ "{{" }}HOMEPAGE_VAR_PROXMOX_PASSWORD{{ "}}" }}
                      fields: ["vms", "resources.cpu", "resources.mem"]
                - TrueNAS:
                    icon: truenas-scale.png
                    href: https://truenas.nasenov.dev
                    widget:
                      type: truenas
                      url: http://192.168.0.15
                      key: {{ "{{" }}HOMEPAGE_VAR_TRUENAS_KEY{{ "}}" }}
                      fields: ["load", "uptime", "alerts"]
                - Rook:
                    icon: rook.png
                    href: https://rook.nasenov.dev
                - MinIO:
                    icon: minio.png
                    href: https://minio.nasenov.dev

            - Monitoring:
                - Grafana:
                    icon: grafana.png
                    href: https://grafana.nasenov.dev
                    widget:
                      type: grafana
                      url: http://grafana.monitoring.svc.cluster.local
                      username: {{ "{{" }}HOMEPAGE_VAR_GRAFANA_ADMIN_USER{{ "}}" }}
                      password: {{ "{{" }}HOMEPAGE_VAR_GRAFANA_ADMIN_PASSWORD{{ "}}" }}
                      fields: ["dashboards", "datasources"]
                - Prometheus:
                    icon: prometheus.png
                    href: https://prometheus.nasenov.dev
                    widget:
                      type: prometheus
                      url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
                      fields: ["targets_up", "targets_down"]
                - Alertmanager:
                    icon: alertmanager.png
                    href: https://alertmanager.nasenov.dev
                - Hubble:
                    icon: cilium.png
                    href: https://hubble.nasenov.dev
                - Alloy:
                    icon: alloy.png
                    href: https://alloy.nasenov.dev

            - Automation:
              - Home Assistant:
                  icon: home-assistant.png
                  href: https://hass.nasenov.dev
                  widget:
                    type: homeassistant
                    url: http://home-assistant.default.svc.cluster.local
                    key: {{ "{{" }}HOMEPAGE_VAR_HOME_ASSISTANT_TOKEN{{ "}}" }}
                    fields: ["people_home", "lights_on", "switches_on"] # supports custom fields
              - Zigbee2MQTT:
                  icon: zigbee2mqtt.png
                  href: https://zigbee.nasenov.dev
              - EMQX:
                  icon: emqx.png
                  href: https://emqx.nasenov.dev
          settings.yaml: |
            ---
            background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
            # theme: dark
            # color: slate
            hideVersion: true

            # fiveColumns: true
            disableCollapse: true

            layout:
              Media:
                style: row
                columns: 4
              Infrastructure:
                style: row
                columns: 2
              Monitoring:
                style: row
                columns: 4
              Automation:
                style: row
                columns: 4
          widgets.yaml: |
            ---
            - logo:
                icon: homepage.png
