---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: openebs
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false

    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false

    localpv-provisioner:
      hostpathClass:
        xfsQuota:
          enabled: true
      analytics:
        enabled: false
