# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.1
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      enableServiceLinks: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      home-assistant:
        type: statefulset

        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              accessMode: ReadWriteOnce
              dataSourceRef:
                apiGroup: volsync.backube
                kind: ReplicationDestination
                name: home-assistant-dst
              size: 1Gi
              storageClass: ceph-block

        containers:
          app:
            image:
              repository: homeassistant/home-assistant
              tag: 2025.2.4
            env:
              TZ: Europe/Sofia
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 512Mi

          codeserver:
            dependsOn: app
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.96.4
            env:
              TZ: Europe/Sofia
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - "/config"
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 128Mi

    service:
      app:
        controller: home-assistant
        primary: true
        ports:
          http:
            port: 80
            targetPort: 8123
      codeserver:
        controller: home-assistant
        primary: false
        type: ClusterIP
        ports:
          http:
            port: 80
            targetPort: 8080

    ingress:
      app:
        className: nginx
        hosts:
          - host: hass.nasenov.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - hass.nasenov.dev
      codeserver:
        className: nginx
        hosts:
          - host: hass-code.nasenov.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: codeserver
                  port: http
        tls:
          - hosts:
              - hass-code.nasenov.dev
