---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
spec:
  targetNamespace: rook-ceph
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  path: ./kubernetes/apps/rook-ceph/rook-ceph/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name:  rook-ceph-cluster
spec:
  targetNamespace: rook-ceph
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
    - name: snapshot-controller
      namespace: storage
  path: ./kubernetes/apps/rook-ceph/rook-ceph/cluster
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  healthCheckExprs:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      current: status.ceph.health == 'HEALTH_OK'
      failed: status.ceph.health == 'HEALTH_ERR'
