---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-dashboard-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: rook-ceph-dashboard-password # rook-ceph expects this name
    template:
      data:
        password: "{{ .ROOK_DASHBOARD_PASSWORD }}"
  data:
    - secretKey: ROOK_DASHBOARD_PASSWORD
      remoteRef:
        key: ROOK_DASHBOARD_PASSWORD
