---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:  
  interval: 30m
  chart:
    spec:
      chart: rook-ceph
      version: v1.16.6
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/rook/ceph  
  
    monitoring:
      enabled: true
