---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 10m0s
  chart:
    spec:
      chart: external-secrets
      version: 0.14.3
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    bitwarden-sdk-server:
      enabled: true
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch        
        seccompProfile: { type: RuntimeDefault }
        capabilities:
          drop:
            - ALL

    serviceMonitor:
      enabled: true
